application: muzigen
version: 1
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# handlers:
# - url: /
# static_files: main.html
# upload: (フォルダやらファイルのパス)
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /package
  static_dir: package

- url: /dart
  static_dir: dart

- url: /html
  static_dir: html

- url: /_ah/channel/connected/
  script: _go_app

- url: /_ah/channel/disconnected/
  script: _go_app

- url: /.*
  script: _go_app
  #login: required


